import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Top Navbar */}
          <Navbar />

          {/* Main content with Sidebar and Dashboard */}
          <div className="flex flex-1">
            {/* Sidebar */}
            <Sidebar />

            {/* Page Content */}
            <main className="flex-1 p-4 bg-[#F9FAFB]">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
